
enable: True

models:
  - school_location
  - workplace_location
  - auto_ownership
  - free_parking
  - cdap
  - mandatory_tour_frequency
  - mandatory_tour_scheduling_work
  - mandatory_tour_scheduling_school
  - joint_tour_frequency
  - tour_mode_choice

model_settings:

  school_location:
    override_choices:
      file_name: estimation_choices/override_persons.csv
      column_name: school_taz
    omnibus_tables:
      choosers_combined:
        - choosers
        - override_choices
      alternatives_combined:
       - alternatives
       - interaction_expression_values
    omnibus_tables_append_columns: [choosers_combined]

  workplace_location:
    override_choices:
      file_name: estimation_choices/override_persons.csv
      column_name: workplace_taz
    omnibus_tables:
      choosers_combined:
        - choosers
        - override_choices
      alternatives_combined:
       - alternatives
       - interaction_expression_values
    omnibus_tables_append_columns: [choosers_combined]

  auto_ownership:
    override_choices:
      file_name: estimation_choices/override_households.csv
      column_name: auto_ownership
    omnibus_tables:
      values_combined:
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  free_parking:
    override_choices:
      file_name: estimation_choices/override_persons.csv
      column_name: free_parking_at_work
    omnibus_tables:
      values_combined:
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  cdap:
    override_choices:
      file_name: estimation_choices/override_persons.csv
      column_name: cdap_activity
    omnibus_tables:
      values_combined:
        - override_choices
        - choosers
    omnibus_tables_append_columns: [values_combined]

  mandatory_tour_frequency:
    override_choices:
      file_name: estimation_choices/override_persons.csv
      column_name: mandatory_tour_frequency
    omnibus_tables:
      values_combined:
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  mandatory_tour_scheduling_work:
    override_choices:
      file_name: estimation_choices/override_tours.csv
      column_name: tdd
    omnibus_tables:
      choosers_combined:
        - choosers
        - override_choices
      alternatives_combined:
       - alternatives
       - interaction_expression_values
    omnibus_tables_append_columns: [choosers_combined]

  mandatory_tour_scheduling_school:
    override_choices:
      file_name: estimation_choices/override_tours.csv
      column_name: tdd
    omnibus_tables:
      choosers_combined:
        - choosers
        - override_choices
      alternatives_combined:
       - alternatives
       - interaction_expression_values
    omnibus_tables_append_columns: [choosers_combined]

  joint_tour_frequency:
    override_choices:
      file_name: estimation_choices/override_households.csv
      column_name: joint_tour_frequency
    omnibus_tables:
      values_combined:
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  joint_tour_composition:
    override_choices:
      file_name: estimation_choices/override_tours.csv
      column_name: composition
    omnibus_tables:
      values_combined:
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  tour_mode_choice:
    # can't override choices because prior model overrides not implemented
#    override_choices:
#      file_name: estimation_choices/override_tours.csv
#      column_name: tour_mode
    omnibus_tables:
      values_combined:
        - override_choices
        #- choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

